"""phase1 schema

Revision ID: 02b39bad0a95
Revises: 
Create Date: 2026-03-15 14:41:11.996290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02b39bad0a95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permit_cases',
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('case_state', sa.Text(), nullable=False),
    sa.Column('review_state', sa.Text(), nullable=False),
    sa.Column('submission_mode', sa.Text(), nullable=False),
    sa.Column('portal_support_level', sa.Text(), nullable=False),
    sa.Column('current_package_id', sa.Text(), nullable=True),
    sa.Column('current_release_profile', sa.Text(), nullable=False),
    sa.Column('legal_hold', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('closure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_permit_cases_project_id'), 'permit_cases', ['project_id'], unique=False)
    op.create_table('release_bundles',
    sa.Column('release_id', sa.Text(), nullable=False),
    sa.Column('spec_version', sa.Text(), nullable=False),
    sa.Column('app_version', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('policy_bundle_version', sa.Text(), nullable=False),
    sa.Column('invariant_pack_version', sa.Text(), nullable=False),
    sa.Column('adapter_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact_digests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approvals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('release_id')
    )
    op.create_table('case_transition_ledger',
    sa.Column('transition_id', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('from_state', sa.Text(), nullable=True),
    sa.Column('to_state', sa.Text(), nullable=True),
    sa.Column('actor_type', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['permit_cases.case_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('transition_id')
    )
    op.create_index(op.f('ix_case_transition_ledger_case_id'), 'case_transition_ledger', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_transition_ledger_correlation_id'), 'case_transition_ledger', ['correlation_id'], unique=False)
    op.create_table('contradiction_artifacts',
    sa.Column('contradiction_id', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('source_a', sa.Text(), nullable=False),
    sa.Column('source_b', sa.Text(), nullable=False),
    sa.Column('ranking_relation', sa.Text(), nullable=False),
    sa.Column('blocking_effect', sa.Boolean(), nullable=False),
    sa.Column('resolution_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['permit_cases.case_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('contradiction_id')
    )
    op.create_index(op.f('ix_contradiction_artifacts_case_id'), 'contradiction_artifacts', ['case_id'], unique=False)
    op.create_table('evidence_artifacts',
    sa.Column('artifact_id', sa.Text(), nullable=False),
    sa.Column('artifact_class', sa.Text(), nullable=False),
    sa.Column('producing_service', sa.Text(), nullable=True),
    sa.Column('linked_case_id', sa.Text(), nullable=True),
    sa.Column('linked_object_id', sa.Text(), nullable=True),
    sa.Column('authoritativeness', sa.Text(), nullable=False),
    sa.Column('retention_class', sa.Text(), nullable=False),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legal_hold_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['linked_case_id'], ['permit_cases.case_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_index(op.f('ix_evidence_artifacts_linked_case_id'), 'evidence_artifacts', ['linked_case_id'], unique=False)
    op.create_index(op.f('ix_evidence_artifacts_linked_object_id'), 'evidence_artifacts', ['linked_object_id'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('parcel_id', sa.Text(), nullable=True),
    sa.Column('project_type', sa.Text(), nullable=False),
    sa.Column('system_size_kw', sa.Double(), nullable=False),
    sa.Column('battery_flag', sa.Boolean(), nullable=False),
    sa.Column('service_upgrade_flag', sa.Boolean(), nullable=False),
    sa.Column('trenching_flag', sa.Boolean(), nullable=False),
    sa.Column('structural_modification_flag', sa.Boolean(), nullable=False),
    sa.Column('roof_type', sa.Text(), nullable=True),
    sa.Column('occupancy_classification', sa.Text(), nullable=True),
    sa.Column('utility_name', sa.Text(), nullable=True),
    sa.Column('contact_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['permit_cases.case_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('release_artifacts',
    sa.Column('artifact_id', sa.Text(), nullable=False),
    sa.Column('release_id', sa.Text(), nullable=False),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['release_bundles.release_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_index(op.f('ix_release_artifacts_release_id'), 'release_artifacts', ['release_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('decision_id', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('object_type', sa.Text(), nullable=False),
    sa.Column('object_id', sa.Text(), nullable=False),
    sa.Column('decision_outcome', sa.Text(), nullable=False),
    sa.Column('reviewer_id', sa.Text(), nullable=False),
    sa.Column('reviewer_independence_status', sa.Text(), nullable=False),
    sa.Column('evidence_ids', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('contradiction_resolution', sa.Text(), nullable=True),
    sa.Column('dissent_flag', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['permit_cases.case_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('decision_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_review_decisions_case_id'), 'review_decisions', ['case_id'], unique=False)
    op.create_index('ix_review_decisions_object', 'review_decisions', ['object_type', 'object_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_decisions_object', table_name='review_decisions')
    op.drop_index(op.f('ix_review_decisions_case_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_release_artifacts_release_id'), table_name='release_artifacts')
    op.drop_table('release_artifacts')
    op.drop_table('projects')
    op.drop_index(op.f('ix_evidence_artifacts_linked_object_id'), table_name='evidence_artifacts')
    op.drop_index(op.f('ix_evidence_artifacts_linked_case_id'), table_name='evidence_artifacts')
    op.drop_table('evidence_artifacts')
    op.drop_index(op.f('ix_contradiction_artifacts_case_id'), table_name='contradiction_artifacts')
    op.drop_table('contradiction_artifacts')
    op.drop_index(op.f('ix_case_transition_ledger_correlation_id'), table_name='case_transition_ledger')
    op.drop_index(op.f('ix_case_transition_ledger_case_id'), table_name='case_transition_ledger')
    op.drop_table('case_transition_ledger')
    op.drop_table('release_bundles')
    op.drop_index(op.f('ix_permit_cases_project_id'), table_name='permit_cases')
    op.drop_table('permit_cases')
    # ### end Alembic commands ###
