"""emergency_override_artifacts

Revision ID: 37a1384857bd
Revises: b1c2d3e4f5a6
Create Date: 2026-03-16 20:41:54.349477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37a1384857bd'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_records',
    sa.Column('emergency_id', sa.Text(), nullable=False),
    sa.Column('incident_id', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('declared_by', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('allowed_bypasses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('forbidden_bypasses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cleanup_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['permit_cases.case_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('emergency_id')
    )
    op.create_index('ix_emergency_records_case_expires', 'emergency_records', ['case_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_emergency_records_case_id'), 'emergency_records', ['case_id'], unique=False)
    op.create_table('override_artifacts',
    sa.Column('override_id', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('affected_surfaces', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approver_id', sa.Text(), nullable=False),
    sa.Column('cleanup_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['permit_cases.case_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('override_id')
    )
    op.create_index('ix_override_artifacts_case_expires', 'override_artifacts', ['case_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_override_artifacts_case_id'), 'override_artifacts', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_override_artifacts_case_id'), table_name='override_artifacts')
    op.drop_index('ix_override_artifacts_case_expires', table_name='override_artifacts')
    op.drop_table('override_artifacts')
    op.drop_index(op.f('ix_emergency_records_case_id'), table_name='emergency_records')
    op.drop_index('ix_emergency_records_case_expires', table_name='emergency_records')
    op.drop_table('emergency_records')
    # ### end Alembic commands ###
