"""legal holds

Revision ID: a06baa922883
Revises: c1fc8c772c8d
Create Date: 2026-03-15 15:05:07.564142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a06baa922883'
down_revision: Union[str, Sequence[str], None] = 'c1fc8c772c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_holds',
    sa.Column('hold_id', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.Text(), nullable=False),
    sa.Column('authorized_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.PrimaryKeyConstraint('hold_id')
    )
    op.create_table('legal_hold_bindings',
    sa.Column('binding_id', sa.Text(), nullable=False),
    sa.Column('hold_id', sa.Text(), nullable=False),
    sa.Column('artifact_id', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(artifact_id IS NOT NULL AND case_id IS NULL) OR (artifact_id IS NULL AND case_id IS NOT NULL)', name='ck_legal_hold_bindings_exactly_one_target'),
    sa.ForeignKeyConstraint(['artifact_id'], ['evidence_artifacts.artifact_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['permit_cases.case_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hold_id'], ['legal_holds.hold_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('binding_id')
    )
    op.create_index(op.f('ix_legal_hold_bindings_artifact_id'), 'legal_hold_bindings', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_legal_hold_bindings_case_id'), 'legal_hold_bindings', ['case_id'], unique=False)
    op.create_index(op.f('ix_legal_hold_bindings_hold_id'), 'legal_hold_bindings', ['hold_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_hold_bindings_hold_id'), table_name='legal_hold_bindings')
    op.drop_index(op.f('ix_legal_hold_bindings_case_id'), table_name='legal_hold_bindings')
    op.drop_index(op.f('ix_legal_hold_bindings_artifact_id'), table_name='legal_hold_bindings')
    op.drop_table('legal_hold_bindings')
    op.drop_table('legal_holds')
    # ### end Alembic commands ###
