"""evidence content metadata

Revision ID: c1fc8c772c8d
Revises: 02b39bad0a95
Create Date: 2026-03-15 14:56:45.667304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1fc8c772c8d'
down_revision: Union[str, Sequence[str], None] = '02b39bad0a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_artifacts', sa.Column('content_bytes', sa.BigInteger(), nullable=True))
    op.add_column('evidence_artifacts', sa.Column('content_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence_artifacts', 'content_type')
    op.drop_column('evidence_artifacts', 'content_bytes')
    # ### end Alembic commands ###
