#!/usr/bin/env bash
# shellcheck shell=bash
set -euo pipefail

# M003 / S03 runbook verification: Contradiction artifacts + advancement blocking.
#
# What this does:
#   1) Ensures docker compose services are up (Postgres + API — no Temporal worker needed)
#   2) Applies Alembic migrations
#   3) Starts the FastAPI server (uvicorn sps.api.main:app)
#   4) Seeds a PermitCase + ReviewDecision via psql (so the advancement guard
#      has a valid review to fall through to if contradiction guard doesn't fire)
#   5) POST /api/v1/contradictions/ → assert 201
#   6) assert_postgres: contradiction_artifacts row exists with resolution_status=OPEN
#   7) POST /api/v1/contradictions/{id}/resolve → assert 200
#   8) assert_postgres: resolution_status=RESOLVED, resolved_at populated
#   9) Seed a fresh PermitCase + ReviewDecision for advancement test
#  10) POST create blocking contradiction for fresh case → 201
#  11) Seed a second ReviewDecision and attempt advancement → expect denial (CONTRADICTION_ADVANCE_DENIED)
#  12) Resolve contradiction → 200
#  13) Re-run advancement → assert CASE_STATE_CHANGED in case_transition_ledger
#  14) Verify 401 on missing/wrong API key
#
# Key differences from m003_s01:
#   - No Temporal worker or workflow started — contradiction guard is pure DB
#   - apply_state_transition called via python -c (no Temporal context required)
#   - Advancement assertion uses case_transition_ledger (no workflow polling)
#
# Expected env vars (optional; defaults match src/sps/config.py and .env.example):
#   SPS_DB_HOST (default: localhost)
#   SPS_DB_PORT (default: 5432)
#   SPS_DB_NAME (default: sps)
#   SPS_DB_USER (default: sps)
#   SPS_DB_PASSWORD (default: sps)          # never printed
#
#   SPS_REVIEWER_API_KEY (default: dev-reviewer-key)
#
#   API_HOST (default: localhost)
#   API_PORT (default: 8000)
#
# Optional overrides:
#   PYTHON (default: ./.venv/bin/python)
#   ALEMBIC (default: ./.venv/bin/alembic)
#   CASE_ID (default: autogenerated)

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# shellcheck source=scripts/lib/assert_postgres.sh
source "$ROOT_DIR/scripts/lib/assert_postgres.sh"

PYTHON="${PYTHON:-$ROOT_DIR/.venv/bin/python}"
ALEMBIC="${ALEMBIC:-$ROOT_DIR/.venv/bin/alembic}"

if [[ ! -x "$PYTHON" ]]; then
  echo "runbook.fail: python_not_found path=$PYTHON" >&2
  exit 2
fi

if [[ ! -x "$ALEMBIC" ]]; then
  echo "runbook.fail: alembic_not_found path=$ALEMBIC" >&2
  exit 2
fi

# Reviewer API key — never printed or echoed.
REVIEWER_API_KEY="${SPS_REVIEWER_API_KEY:-dev-reviewer-key}"
API_HOST="${API_HOST:-localhost}"
API_PORT="${API_PORT:-8000}"
API_BASE="http://${API_HOST}:${API_PORT}"

API_PID=""
API_LOG=""

_cleanup() {
  local exit_code=$?

  if [[ -n "$API_PID" ]]; then
    if kill -0 "$API_PID" >/dev/null 2>&1; then
      echo "runbook.cleanup: stopping_api pid=$API_PID" >&2
      kill "$API_PID" >/dev/null 2>&1 || true
      wait "$API_PID" >/dev/null 2>&1 || true
    fi
  fi

  if [[ $exit_code -ne 0 ]]; then
    if [[ -n "$API_LOG" && -f "$API_LOG" ]]; then
      echo "runbook.diagnostics: api_log_tail path=$API_LOG" >&2
      tail -n 50 "$API_LOG" >&2 || true
    fi
  fi

  return $exit_code
}
trap _cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

_wait_for_api_ready() {
  local timeout_seconds="$1"

  local deadline=$((SECONDS + timeout_seconds))
  while (( SECONDS < deadline )); do
    if [[ -n "$API_PID" ]] && ! kill -0 "$API_PID" >/dev/null 2>&1; then
      echo "runbook.fail: api_exited_early pid=$API_PID" >&2
      return 1
    fi

    if "$PYTHON" - <<'PY' 2>/dev/null
import os, socket
try:
    with socket.create_connection(("localhost", int(os.environ.get("API_PORT", "8000"))), timeout=0.5):
        pass
    exit(0)
except OSError:
    exit(1)
PY
    then
      return 0
    fi

    sleep 0.2
  done

  echo "runbook.fail: api_not_ready timeout_seconds=$timeout_seconds" >&2
  return 1
}

_http_post_json() {
  # POST a JSON body and return the HTTP status code on stdout.
  # The response body goes to the file referenced by HTTP_RESPONSE_FILE.
  local url="$1"
  local body="$2"
  local api_key="$3"
  local out_file="${HTTP_RESPONSE_FILE:-/tmp/m003_s03_response_$$.json}"

  curl -s -o "$out_file" -w "%{http_code}" \
    -X POST "$url" \
    -H "Content-Type: application/json" \
    -H "X-Reviewer-Api-Key: ${api_key}" \
    -d "$body"
}

_assert_http_status() {
  local actual="$1"
  local expected="$2"
  local label="$3"

  if [[ "$actual" != "$expected" ]]; then
    echo "runbook.fail: http_status_mismatch label=$label expected=$expected actual=$actual" >&2
    if [[ -f "${HTTP_RESPONSE_FILE:-}" ]]; then
      echo "runbook.diagnostics: response_body" >&2
      cat "${HTTP_RESPONSE_FILE}" >&2 || true
    fi
    exit 1
  fi
}

# ---------------------------------------------------------------------------
# Phase 1: Ensure infrastructure is up (Postgres + API only — no Temporal)
# ---------------------------------------------------------------------------

echo "runbook: ensuring_docker_compose_stack" >&2
docker compose up -d postgres >/dev/null

DB_HOST="${SPS_DB_HOST:-127.0.0.1}"
DB_PORT="${SPS_DB_PORT:-5432}"

# Wait for Postgres TCP.
WAIT_HOST="$DB_HOST" WAIT_PORT="$DB_PORT" WAIT_TIMEOUT_SECONDS=30 \
  "$PYTHON" - <<'PY'
import os, socket, time, sys
host = os.environ["WAIT_HOST"]
port = int(os.environ["WAIT_PORT"])
timeout_seconds = float(os.environ["WAIT_TIMEOUT_SECONDS"])
deadline = time.time() + timeout_seconds
last_err = None
while time.time() < deadline:
    try:
        with socket.create_connection((host, port), timeout=1.0):
            sys.exit(0)
    except OSError as e:
        last_err = e
        time.sleep(0.2)
print(
    f"runbook.fail: postgres_not_ready host={host} port={port} last_err={type(last_err).__name__ if last_err else None}",
    file=sys.stderr,
)
sys.exit(1)
PY

# ---------------------------------------------------------------------------
# Phase 2: Migrations
# ---------------------------------------------------------------------------

echo "runbook: applying_migrations" >&2
"$ALEMBIC" upgrade head >/dev/null

# ---------------------------------------------------------------------------
# Phase 3: Start FastAPI server
# ---------------------------------------------------------------------------

mkdir -p "$ROOT_DIR/artifacts/runbook"
API_LOG="$ROOT_DIR/artifacts/runbook/m003_s03_api_$(date +%Y%m%d_%H%M%S)_$$.log"

echo "runbook: starting_api log=$API_LOG port=$API_PORT" >&2
"$PYTHON" -m uvicorn sps.api.main:app --host 0.0.0.0 --port "$API_PORT" >"$API_LOG" 2>&1 &
API_PID=$!

_wait_for_api_ready 30
echo "runbook: api_ready pid=$API_PID" >&2

# ---------------------------------------------------------------------------
# Phase 4: Seed Postgres for the core contradiction scenario
# ---------------------------------------------------------------------------

CASE_ID="${CASE_ID:-M003-S03-$(date +%Y%m%d%H%M%S)-$$}"
CONTRADICTION_ID="CONTRA-${CASE_ID}"
DECISION_ID="DEC-${CASE_ID}"

echo "runbook: seeding_permit_case case_id=$CASE_ID" >&2

# Seed via Python (avoids psql syntax complexity for structured JSON fields).
"$PYTHON" - <<PY
import sys, os
sys.path.insert(0, "$ROOT_DIR/src")
os.environ.setdefault("SPS_DB_HOST", "${SPS_DB_HOST:-localhost}")
os.environ.setdefault("SPS_DB_PORT", "${SPS_DB_PORT:-5432}")
os.environ.setdefault("SPS_DB_NAME", "${SPS_DB_NAME:-sps}")
os.environ.setdefault("SPS_DB_USER", "${SPS_DB_USER:-sps}")
os.environ.setdefault("SPS_DB_PASSWORD", "${SPS_DB_PASSWORD:-sps}")

import datetime as dt
from sps.db.models import PermitCase, ReviewDecision
from sps.db.session import get_sessionmaker

SessionLocal = get_sessionmaker()
with SessionLocal() as session:
    # Clean slate for this case_id.
    existing = session.get(PermitCase, "$CASE_ID")
    if existing is None:
        session.add(PermitCase(
            case_id="$CASE_ID",
            tenant_id="tenant-runbook",
            project_id="project-$CASE_ID",
            case_state="REVIEW_PENDING",
            review_state="PENDING",
            submission_mode="DIGITAL",
            portal_support_level="FULL",
            current_release_profile="default",
        ))
    dec = session.get(ReviewDecision, "$DECISION_ID")
    if dec is None:
        session.add(ReviewDecision(
            decision_id="$DECISION_ID",
            schema_version="1.0",
            case_id="$CASE_ID",
            object_type="permit_case",
            object_id="$CASE_ID",
            idempotency_key="idem/$DECISION_ID",
            reviewer_id="reviewer-runbook",
            decision_outcome="ACCEPT",
            reviewer_independence_status="PASS",
            dissent_flag=False,
            decision_at=dt.datetime.now(tz=dt.UTC),
        ))
    session.commit()
print("seed.ok")
PY

echo "runbook: permit_case_seeded case_id=$CASE_ID" >&2

# ---------------------------------------------------------------------------
# Phase 5: POST create blocking contradiction → assert 201
# ---------------------------------------------------------------------------

HTTP_RESPONSE_FILE="$(mktemp /tmp/m003_s03_resp_XXXXXX)"
export HTTP_RESPONSE_FILE

CONTRA_BODY="$(cat <<JSON
{
  "contradiction_id": "${CONTRADICTION_ID}",
  "case_id": "${CASE_ID}",
  "scope": "zoning",
  "source_a": "applicant-submission",
  "source_b": "municipal-code-ref",
  "ranking_relation": "A_SUPERSEDES_B",
  "blocking_effect": true
}
JSON
)"

echo "runbook: posting_create_contradiction contradiction_id=$CONTRADICTION_ID" >&2

HTTP_STATUS="$(_http_post_json \
  "${API_BASE}/api/v1/contradictions/" \
  "$CONTRA_BODY" \
  "$REVIEWER_API_KEY")"

_assert_http_status "$HTTP_STATUS" "201" "create_contradiction"
echo "runbook: create_contradiction_201_ok" >&2

if [[ -f "$HTTP_RESPONSE_FILE" ]]; then
  cat "$HTTP_RESPONSE_FILE"
  echo
fi

# ---------------------------------------------------------------------------
# Phase 6: Assert contradiction_artifacts row in Postgres
# ---------------------------------------------------------------------------

pg_assert_no_single_quotes "$CONTRADICTION_ID"
pg_assert_no_single_quotes "$CASE_ID"
CONTRA_QUOTED="$(pg_sql_quote "$CONTRADICTION_ID")"
CASE_QUOTED="$(pg_sql_quote "$CASE_ID")"

echo "runbook: asserting_contradiction_artifacts_row" >&2

pg_assert_int_eq \
  "select count(*) from contradiction_artifacts where contradiction_id=${CONTRA_QUOTED}" \
  "1" \
  "contradiction_artifacts.count"

pg_assert_scalar_eq \
  "select resolution_status from contradiction_artifacts where contradiction_id=${CONTRA_QUOTED}" \
  "OPEN" \
  "contradiction_artifacts.resolution_status"

pg_assert_scalar_eq \
  "select blocking_effect from contradiction_artifacts where contradiction_id=${CONTRA_QUOTED}" \
  "t" \
  "contradiction_artifacts.blocking_effect"

echo "runbook: contradiction_artifacts_row_ok" >&2

# ---------------------------------------------------------------------------
# Phase 7: POST resolve → assert 200
# ---------------------------------------------------------------------------

RESOLVE_BODY='{"resolved_by": "reviewer-runbook"}'

HTTP_RESPONSE_FILE="$(mktemp /tmp/m003_s03_resolve_XXXXXX)"
export HTTP_RESPONSE_FILE

echo "runbook: posting_resolve_contradiction contradiction_id=$CONTRADICTION_ID" >&2

RESOLVE_STATUS="$(curl -s -o "$HTTP_RESPONSE_FILE" -w "%{http_code}" \
  -X POST "${API_BASE}/api/v1/contradictions/${CONTRADICTION_ID}/resolve" \
  -H "Content-Type: application/json" \
  -H "X-Reviewer-Api-Key: ${REVIEWER_API_KEY}" \
  -d "$RESOLVE_BODY")"

_assert_http_status "$RESOLVE_STATUS" "200" "resolve_contradiction"
echo "runbook: resolve_contradiction_200_ok" >&2

if [[ -f "$HTTP_RESPONSE_FILE" ]]; then
  cat "$HTTP_RESPONSE_FILE"
  echo
fi

# ---------------------------------------------------------------------------
# Phase 8: Assert resolution_status=RESOLVED in Postgres
# ---------------------------------------------------------------------------

echo "runbook: asserting_contradiction_resolved" >&2

pg_assert_scalar_eq \
  "select resolution_status from contradiction_artifacts where contradiction_id=${CONTRA_QUOTED}" \
  "RESOLVED" \
  "contradiction_artifacts.resolution_status_after_resolve"

# resolved_at must be non-null after resolve.
RESOLVED_AT="$(pg_exec "select resolved_at from contradiction_artifacts where contradiction_id=${CONTRA_QUOTED}" || echo "")"
RESOLVED_AT="${RESOLVED_AT%$'\n'}"
if [[ -z "$RESOLVED_AT" ]]; then
  echo "postgres.assert.fail: resolved_at_is_null contradiction_id=${CONTRADICTION_ID}" >&2
  exit 1
fi

pg_assert_scalar_eq \
  "select resolved_by from contradiction_artifacts where contradiction_id=${CONTRA_QUOTED}" \
  "reviewer-runbook" \
  "contradiction_artifacts.resolved_by"

echo "runbook: contradiction_resolved_ok" >&2

# ---------------------------------------------------------------------------
# Phase 9: Prove advancement unblocked — apply_state_transition via Python
# ---------------------------------------------------------------------------

echo "runbook: proving_advancement_unblocked case_id=$CASE_ID decision_id=$DECISION_ID" >&2

ADVANCEMENT_RESULT="$("$PYTHON" - <<PY
import sys, os, uuid, datetime as dt
sys.path.insert(0, "$ROOT_DIR/src")
os.environ.setdefault("SPS_DB_HOST", "${SPS_DB_HOST:-localhost}")
os.environ.setdefault("SPS_DB_PORT", "${SPS_DB_PORT:-5432}")
os.environ.setdefault("SPS_DB_NAME", "${SPS_DB_NAME:-sps}")
os.environ.setdefault("SPS_DB_USER", "${SPS_DB_USER:-sps}")
os.environ.setdefault("SPS_DB_PASSWORD", "${SPS_DB_PASSWORD:-sps}")

from sps.workflows.permit_case.activities import apply_state_transition
from sps.workflows.permit_case.contracts import (
    ActorType, AppliedStateTransitionResult, CaseState, StateTransitionRequest,
)

req = StateTransitionRequest(
    request_id=str(uuid.uuid4()),
    case_id="$CASE_ID",
    from_state=CaseState.REVIEW_PENDING,
    to_state=CaseState.APPROVED_FOR_SUBMISSION,
    actor_type=ActorType.reviewer,
    actor_id="reviewer-runbook",
    correlation_id=str(uuid.uuid4()),
    required_review_id="$DECISION_ID",
    required_evidence_ids=[],
    requested_at=dt.datetime.now(tz=dt.UTC),
)

result = apply_state_transition(req)
print(result.event_type)
PY
)"

echo "runbook: advancement_result event_type=$ADVANCEMENT_RESULT" >&2

if [[ "$ADVANCEMENT_RESULT" != "CASE_STATE_CHANGED" ]]; then
  echo "runbook.fail: advancement_not_unblocked expected=CASE_STATE_CHANGED actual=$ADVANCEMENT_RESULT" >&2
  exit 1
fi

echo "runbook: advancement_unblocked_ok event_type=$ADVANCEMENT_RESULT" >&2

# Assert ledger row in Postgres.
pg_assert_int_eq \
  "select count(*) from case_transition_ledger where case_id=${CASE_QUOTED} and event_type='CASE_STATE_CHANGED'" \
  "1" \
  "case_transition_ledger.CASE_STATE_CHANGED"

echo "runbook: ledger_row_ok" >&2

# ---------------------------------------------------------------------------
# Phase 10: GET contradiction — read-only inspection surface
# ---------------------------------------------------------------------------

echo "runbook: verifying_get_contradiction" >&2
GET_STATUS="$(curl -s -o /tmp/m003_s03_get_resp_$$.json -w "%{http_code}" \
  "${API_BASE}/api/v1/contradictions/${CONTRADICTION_ID}" \
  -H "X-Reviewer-Api-Key: ${REVIEWER_API_KEY}")"

if [[ "$GET_STATUS" != "200" ]]; then
  echo "runbook.fail: get_contradiction expected=200 actual=$GET_STATUS" >&2
  exit 1
fi
echo "runbook: get_contradiction_200_ok" >&2

# ---------------------------------------------------------------------------
# Phase 11: Failure path verification — 401 on missing/wrong API key
# ---------------------------------------------------------------------------

echo "runbook: verifying_401_on_missing_key" >&2
STATUS_401_MISSING="$(curl -s -o /dev/null -w "%{http_code}" \
  -X POST "${API_BASE}/api/v1/contradictions/" \
  -H "Content-Type: application/json" \
  -d '{}')"

_assert_http_status "$STATUS_401_MISSING" "401" "missing_api_key"

echo "runbook: verifying_401_on_wrong_key" >&2
STATUS_401_WRONG="$(curl -s -o /dev/null -w "%{http_code}" \
  -X POST "${API_BASE}/api/v1/contradictions/" \
  -H "Content-Type: application/json" \
  -H "X-Reviewer-Api-Key: wrong-key-definitely-not-valid" \
  -d '{}')"

_assert_http_status "$STATUS_401_WRONG" "401" "wrong_api_key"

echo "runbook: auth_checks_ok" >&2

# ---------------------------------------------------------------------------
# Phase 12: Duplicate create → 409
# ---------------------------------------------------------------------------

echo "runbook: proving_409_duplicate_contradiction" >&2
HTTP_RESPONSE_FILE="$(mktemp /tmp/m003_s03_dup_XXXXXX)"
export HTTP_RESPONSE_FILE

HTTP_STATUS_409="$(_http_post_json \
  "${API_BASE}/api/v1/contradictions/" \
  "$CONTRA_BODY" \
  "$REVIEWER_API_KEY")"

_assert_http_status "$HTTP_STATUS_409" "409" "duplicate_contradiction"
echo "runbook: duplicate_contradiction_409_ok" >&2

# ---------------------------------------------------------------------------
# Phase 13: Final Postgres summary
# ---------------------------------------------------------------------------

echo "runbook: postgres_summary" >&2
pg_print "select contradiction_id, blocking_effect, resolution_status, resolved_by from contradiction_artifacts where case_id=${CASE_QUOTED}" >&2
pg_print "select event_type, to_state from case_transition_ledger where case_id=${CASE_QUOTED} order by occurred_at" >&2

echo "runbook: structured_log_hint hint='docker compose logs api | grep contradiction_api'" >&2

echo "runbook: ok" >&2
