#!/usr/bin/env bash
# shellcheck shell=bash
set -euo pipefail

# M003 / S04 runbook verification: Dissent artifact creation and read endpoint.
#
# What this does:
#   1) Ensures docker compose services are up (Postgres — no Temporal worker needed)
#   2) Applies Alembic migrations
#   3) Starts the FastAPI server (uvicorn sps.api.main:app)
#   4) Seeds a PermitCase via Python
#   5) POST /api/v1/reviews/decisions with outcome=ACCEPT_WITH_DISSENT → assert 201
#   6) Capture dissent_id from response
#   7) GET /api/v1/dissents/{dissent_id} → assert 200
#   8) assert_postgres: dissent_artifacts row exists with resolution_state=OPEN
#   9) POST /api/v1/reviews/decisions with outcome=ACCEPT (new decision, same case) → assert 201
#  10) assert_postgres: no dissent_artifacts row for the ACCEPT decision
#  11) Verify 401 on missing API key
#  12) Cleanup: kill uvicorn
#
# Key differences from m003_s03:
#   - No apply_state_transition calls — dissent artifacts are pure DB (no Temporal)
#   - Verifies dissent_artifacts table directly (new table introduced in S04)
#   - GET /api/v1/dissents/{id} read endpoint tested end-to-end
#
# Expected env vars (optional; defaults match src/sps/config.py and .env.example):
#   SPS_DB_HOST (default: localhost)
#   SPS_DB_PORT (default: 5432)
#   SPS_DB_NAME (default: sps)
#   SPS_DB_USER (default: sps)
#   SPS_DB_PASSWORD (default: sps)          # never printed
#
#   SPS_REVIEWER_API_KEY (default: dev-reviewer-key)
#
#   API_HOST (default: localhost)
#   API_PORT (default: 8000)
#
# Optional overrides:
#   PYTHON (default: ./.venv/bin/python)
#   ALEMBIC (default: ./.venv/bin/alembic)
#   CASE_ID (default: autogenerated)

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# shellcheck source=scripts/lib/assert_postgres.sh
source "$ROOT_DIR/scripts/lib/assert_postgres.sh"

PYTHON="${PYTHON:-$ROOT_DIR/.venv/bin/python}"
ALEMBIC="${ALEMBIC:-$ROOT_DIR/.venv/bin/alembic}"

if [[ ! -x "$PYTHON" ]]; then
  echo "runbook.fail: python_not_found path=$PYTHON" >&2
  exit 2
fi

if [[ ! -x "$ALEMBIC" ]]; then
  echo "runbook.fail: alembic_not_found path=$ALEMBIC" >&2
  exit 2
fi

# Reviewer API key — never printed or echoed.
REVIEWER_API_KEY="${SPS_REVIEWER_API_KEY:-dev-reviewer-key}"
API_HOST="${API_HOST:-localhost}"
API_PORT="${API_PORT:-8000}"
API_BASE="http://${API_HOST}:${API_PORT}"

API_PID=""
API_LOG=""

_cleanup() {
  local exit_code=$?

  if [[ -n "$API_PID" ]]; then
    if kill -0 "$API_PID" >/dev/null 2>&1; then
      echo "runbook.cleanup: stopping_api pid=$API_PID" >&2
      kill "$API_PID" >/dev/null 2>&1 || true
      wait "$API_PID" >/dev/null 2>&1 || true
    fi
  fi

  if [[ $exit_code -ne 0 ]]; then
    if [[ -n "$API_LOG" && -f "$API_LOG" ]]; then
      echo "runbook.diagnostics: api_log_tail path=$API_LOG" >&2
      tail -n 50 "$API_LOG" >&2 || true
    fi
  fi

  return $exit_code
}
trap _cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

_wait_for_api_ready() {
  local timeout_seconds="$1"

  local deadline=$((SECONDS + timeout_seconds))
  while (( SECONDS < deadline )); do
    if [[ -n "$API_PID" ]] && ! kill -0 "$API_PID" >/dev/null 2>&1; then
      echo "runbook.fail: api_exited_early pid=$API_PID" >&2
      return 1
    fi

    if "$PYTHON" - <<'PY' 2>/dev/null
import os, socket
try:
    with socket.create_connection(("localhost", int(os.environ.get("API_PORT", "8000"))), timeout=0.5):
        pass
    exit(0)
except OSError:
    exit(1)
PY
    then
      return 0
    fi

    sleep 0.2
  done

  echo "runbook.fail: api_not_ready timeout_seconds=$timeout_seconds" >&2
  return 1
}

_http_post_json() {
  # POST a JSON body and return the HTTP status code on stdout.
  # The response body goes to the file referenced by HTTP_RESPONSE_FILE.
  local url="$1"
  local body="$2"
  local api_key="$3"
  local out_file="${HTTP_RESPONSE_FILE:-/tmp/sps-s04-response-$$.json}"

  curl -s -o "$out_file" -w "%{http_code}" \
    -X POST "$url" \
    -H "Content-Type: application/json" \
    -H "X-Reviewer-Api-Key: ${api_key}" \
    -d "$body"
}

_assert_http_status() {
  local actual="$1"
  local expected="$2"
  local label="$3"

  if [[ "$actual" != "$expected" ]]; then
    echo "runbook.fail: http_status_mismatch label=$label expected=$expected actual=$actual" >&2
    if [[ -f "${HTTP_RESPONSE_FILE:-}" ]]; then
      echo "runbook.diagnostics: response_body" >&2
      cat "${HTTP_RESPONSE_FILE}" >&2 || true
    fi
    exit 1
  fi
}

# ---------------------------------------------------------------------------
# Phase 1: Ensure infrastructure is up (Postgres + API only — no Temporal)
# ---------------------------------------------------------------------------

echo "runbook: ensuring_docker_compose_stack" >&2
docker compose up -d postgres >/dev/null

DB_HOST="${SPS_DB_HOST:-127.0.0.1}"
DB_PORT="${SPS_DB_PORT:-5432}"

# Wait for Postgres TCP.
WAIT_HOST="$DB_HOST" WAIT_PORT="$DB_PORT" WAIT_TIMEOUT_SECONDS=30 \
  "$PYTHON" - <<'PY'
import os, socket, time, sys
host = os.environ["WAIT_HOST"]
port = int(os.environ["WAIT_PORT"])
timeout_seconds = float(os.environ["WAIT_TIMEOUT_SECONDS"])
deadline = time.time() + timeout_seconds
last_err = None
while time.time() < deadline:
    try:
        with socket.create_connection((host, port), timeout=1.0):
            sys.exit(0)
    except OSError as e:
        last_err = e
        time.sleep(0.2)
print(
    f"runbook.fail: postgres_not_ready host={host} port={port} last_err={type(last_err).__name__ if last_err else None}",
    file=sys.stderr,
)
sys.exit(1)
PY

# ---------------------------------------------------------------------------
# Phase 2: Migrations
# ---------------------------------------------------------------------------

echo "runbook: applying_migrations" >&2
"$ALEMBIC" upgrade head >/dev/null

# ---------------------------------------------------------------------------
# Phase 3: Start FastAPI server
# ---------------------------------------------------------------------------

mkdir -p "$ROOT_DIR/.gsd/runbook"
API_LOG="$ROOT_DIR/.gsd/runbook/m003_s04_api_$(date +%Y%m%d_%H%M%S)_$$.log"

echo "runbook: starting_api log=$API_LOG port=$API_PORT" >&2
"$PYTHON" -m uvicorn sps.api.main:app --host 0.0.0.0 --port "$API_PORT" >"$API_LOG" 2>&1 &
API_PID=$!

_wait_for_api_ready 30
echo "runbook: api_ready pid=$API_PID" >&2

# ---------------------------------------------------------------------------
# Phase 4: Seed PermitCase
# ---------------------------------------------------------------------------

CASE_ID="${CASE_ID:-M003-S04-$(date +%Y%m%d%H%M%S)-$$}"
DECISION_ID="DEC-S04-AWD-${CASE_ID}"
DECISION_ID_2="DEC-S04-ACC-${CASE_ID}"

echo "runbook: seeding_permit_case case_id=$CASE_ID" >&2

"$PYTHON" - <<PY
import sys, os
sys.path.insert(0, "$ROOT_DIR/src")
os.environ.setdefault("SPS_DB_HOST", "${SPS_DB_HOST:-localhost}")
os.environ.setdefault("SPS_DB_PORT", "${SPS_DB_PORT:-5432}")
os.environ.setdefault("SPS_DB_NAME", "${SPS_DB_NAME:-sps}")
os.environ.setdefault("SPS_DB_USER", "${SPS_DB_USER:-sps}")
os.environ.setdefault("SPS_DB_PASSWORD", "${SPS_DB_PASSWORD:-sps}")

from sps.db.models import PermitCase
from sps.db.session import get_sessionmaker

SessionLocal = get_sessionmaker()
with SessionLocal() as session:
    existing = session.get(PermitCase, "$CASE_ID")
    if existing is None:
        session.add(PermitCase(
            case_id="$CASE_ID",
            tenant_id="tenant-runbook",
            project_id="project-$CASE_ID",
            case_state="REVIEW_PENDING",
            review_state="PENDING",
            submission_mode="DIGITAL",
            portal_support_level="FULL",
            current_release_profile="default",
        ))
    session.commit()
print("seed.ok")
PY

echo "runbook: permit_case_seeded case_id=$CASE_ID" >&2

# ---------------------------------------------------------------------------
# Phase 5: POST ACCEPT_WITH_DISSENT decision → assert 201
# ---------------------------------------------------------------------------

HTTP_RESPONSE_FILE="$(mktemp /tmp/sps-s04.XXXXXX)"
export HTTP_RESPONSE_FILE

AWD_BODY="$(cat <<JSON
{
  "decision_id": "${DECISION_ID}",
  "idempotency_key": "idem/${DECISION_ID}",
  "case_id": "${CASE_ID}",
  "reviewer_id": "reviewer-runbook",
  "subject_author_id": "author-of-the-case",
  "outcome": "ACCEPT_WITH_DISSENT",
  "dissent_scope": "structural",
  "dissent_rationale": "runbook structural concern"
}
JSON
)"

echo "runbook: posting_accept_with_dissent decision_id=$DECISION_ID" >&2

HTTP_STATUS="$(_http_post_json \
  "${API_BASE}/api/v1/reviews/decisions" \
  "$AWD_BODY" \
  "$REVIEWER_API_KEY")"

_assert_http_status "$HTTP_STATUS" "201" "create_decision_accept_with_dissent"
echo "runbook: accept_with_dissent_201_ok" >&2

# Capture dissent_id from response.
DISSENT_ID="$("$PYTHON" -c "import json, sys; d=json.load(open('$HTTP_RESPONSE_FILE')); print(d['dissent_artifact_id'])")"
echo "runbook: dissent_id_captured dissent_id=$DISSENT_ID" >&2

if [[ -f "$HTTP_RESPONSE_FILE" ]]; then
  cat "$HTTP_RESPONSE_FILE"
  echo
fi

# ---------------------------------------------------------------------------
# Phase 6: GET /api/v1/dissents/{dissent_id} → assert 200
# ---------------------------------------------------------------------------

GET_RESPONSE_FILE="$(mktemp /tmp/sps-s04.XXXXXX)"

echo "runbook: getting_dissent_artifact dissent_id=$DISSENT_ID" >&2
GET_STATUS="$(curl -s -o "$GET_RESPONSE_FILE" -w "%{http_code}" \
  "${API_BASE}/api/v1/dissents/${DISSENT_ID}" \
  -H "X-Reviewer-Api-Key: ${REVIEWER_API_KEY}")"

if [[ "$GET_STATUS" != "200" ]]; then
  echo "runbook.fail: get_dissent expected=200 actual=$GET_STATUS" >&2
  cat "$GET_RESPONSE_FILE" >&2 || true
  exit 1
fi
echo "runbook: get_dissent_200_ok" >&2

if [[ -f "$GET_RESPONSE_FILE" ]]; then
  cat "$GET_RESPONSE_FILE"
  echo
fi

# ---------------------------------------------------------------------------
# Phase 7: psql assert — dissent_artifacts row: resolution_state=OPEN
# ---------------------------------------------------------------------------

pg_assert_no_single_quotes "$DECISION_ID"
DECISION_QUOTED="$(pg_sql_quote "$DECISION_ID")"

echo "runbook: asserting_dissent_artifacts_row" >&2

pg_assert_scalar_eq \
  "select resolution_state from dissent_artifacts where linked_review_id=${DECISION_QUOTED}" \
  "OPEN" \
  "dissent_artifacts.resolution_state"

pg_assert_int_eq \
  "select count(*) from dissent_artifacts where linked_review_id=${DECISION_QUOTED}" \
  "1" \
  "dissent_artifacts.count"

echo "runbook: dissent_artifacts_row_ok" >&2

# ---------------------------------------------------------------------------
# Phase 8: POST ACCEPT decision (new decision_id, same case) → assert 201
# ---------------------------------------------------------------------------

HTTP_RESPONSE_FILE="$(mktemp /tmp/sps-s04.XXXXXX)"
export HTTP_RESPONSE_FILE

ACC_BODY="$(cat <<JSON
{
  "decision_id": "${DECISION_ID_2}",
  "idempotency_key": "idem/${DECISION_ID_2}",
  "case_id": "${CASE_ID}",
  "reviewer_id": "reviewer-runbook",
  "subject_author_id": "author-of-the-case",
  "outcome": "ACCEPT"
}
JSON
)"

echo "runbook: posting_accept_decision decision_id=$DECISION_ID_2" >&2

HTTP_STATUS_2="$(_http_post_json \
  "${API_BASE}/api/v1/reviews/decisions" \
  "$ACC_BODY" \
  "$REVIEWER_API_KEY")"

_assert_http_status "$HTTP_STATUS_2" "201" "create_decision_accept"
echo "runbook: accept_201_ok" >&2

if [[ -f "$HTTP_RESPONSE_FILE" ]]; then
  cat "$HTTP_RESPONSE_FILE"
  echo
fi

# ---------------------------------------------------------------------------
# Phase 9: psql assert — no dissent_artifacts row for the ACCEPT decision
# ---------------------------------------------------------------------------

pg_assert_no_single_quotes "$DECISION_ID_2"
DECISION_2_QUOTED="$(pg_sql_quote "$DECISION_ID_2")"

echo "runbook: asserting_no_dissent_artifact_for_accept" >&2

pg_assert_int_eq \
  "select count(*) from dissent_artifacts where linked_review_id=${DECISION_2_QUOTED}" \
  "0" \
  "dissent_artifacts.count_for_accept"

echo "runbook: no_dissent_for_accept_ok" >&2

# ---------------------------------------------------------------------------
# Phase 10: Failure path verification — 401 on missing API key
# ---------------------------------------------------------------------------

echo "runbook: verifying_401_on_missing_key" >&2
STATUS_401_MISSING="$(curl -s -o /dev/null -w "%{http_code}" \
  -X POST "${API_BASE}/api/v1/reviews/decisions" \
  -H "Content-Type: application/json" \
  -d '{}')"

_assert_http_status "$STATUS_401_MISSING" "401" "missing_api_key"
echo "runbook: auth_check_ok" >&2

# ---------------------------------------------------------------------------
# Phase 11: Final Postgres summary
# ---------------------------------------------------------------------------

pg_assert_no_single_quotes "$CASE_ID"
CASE_QUOTED="$(pg_sql_quote "$CASE_ID")"

echo "runbook: postgres_summary" >&2
pg_print "select dissent_id, linked_review_id, resolution_state from dissent_artifacts where case_id=${CASE_QUOTED}" >&2

echo "runbook: structured_log_hint hint='docker compose logs api | grep reviewer_api.dissent_artifact_created'" >&2

echo "runbook: ok" >&2
