#!/usr/bin/env bash
# shellcheck shell=bash
set -euo pipefail

# M002 / S03 runbook verification: canonical Temporal stack → worker → reviewer API → Postgres asserts.
#
# What this does:
#   1) Ensures docker compose services are up (Postgres + Temporal + Temporal UI)
#   2) Applies Alembic migrations
#   3) Starts the real worker entrypoint (python -m sps.workflows.worker)
#   4) Starts the real operator CLI (python -m sps.workflows.cli)
#   5) Persists a review decision through the reviewer API and relies on its best-effort signal
#   5) Asserts durable Postgres outcomes for the workflow_id/run_id correlation
#
# Expected env vars (optional; defaults match src/sps/config.py and .env.example):
#   SPS_DB_HOST (default: localhost)
#   SPS_DB_PORT (default: 5432)
#   SPS_DB_NAME (default: sps)
#   SPS_DB_USER (default: sps)
#   SPS_DB_PASSWORD (default: sps)          # never printed
#
#   SPS_TEMPORAL_ADDRESS (default: localhost:7233)
#   SPS_TEMPORAL_NAMESPACE (default: default)
#   SPS_TEMPORAL_TASK_QUEUE (default: sps-permit-case)
#
# Optional overrides:
#   PYTHON (default: ./.venv/bin/python)
#   ALEMBIC (default: ./.venv/bin/alembic)
#   CASE_ID (default: autogenerated)
#   DECISION_OUTCOME (default: ACCEPT)
#   REVIEWER_ID (default: reviewer-runbook)
#   SUBJECT_AUTHOR_ID (default: author-runbook)
#   SPS_REVIEWER_API_KEY (default: dev-reviewer-key)

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# shellcheck source=scripts/lib/assert_postgres.sh
source "$ROOT_DIR/scripts/lib/assert_postgres.sh"

PYTHON="${PYTHON:-$ROOT_DIR/.venv/bin/python}"
ALEMBIC="${ALEMBIC:-$ROOT_DIR/.venv/bin/alembic}"

if [[ ! -x "$PYTHON" ]]; then
  echo "runbook.fail: python_not_found path=$PYTHON" >&2
  exit 2
fi

if [[ ! -x "$ALEMBIC" ]]; then
  echo "runbook.fail: alembic_not_found path=$ALEMBIC" >&2
  exit 2
fi

WORKER_PID=""
WORKER_LOG=""

_cleanup() {
  local exit_code=$?

  if [[ -n "$WORKER_PID" ]]; then
    if kill -0 "$WORKER_PID" >/dev/null 2>&1; then
      echo "runbook.cleanup: stopping_worker pid=$WORKER_PID" >&2
      kill "$WORKER_PID" >/dev/null 2>&1 || true
      wait "$WORKER_PID" >/dev/null 2>&1 || true
    fi
  fi

  if [[ $exit_code -ne 0 ]]; then
    if [[ -n "$WORKER_LOG" && -f "$WORKER_LOG" ]]; then
      echo "runbook.diagnostics: worker_log_tail path=$WORKER_LOG" >&2
      tail -n 50 "$WORKER_LOG" >&2 || true
    fi
  fi

  return $exit_code
}
trap _cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

_wait_for_tcp() {
  local host="$1"
  local port="$2"
  local timeout_seconds="$3"

  WAIT_HOST="$host" WAIT_PORT="$port" WAIT_TIMEOUT_SECONDS="$timeout_seconds" \
    "$PYTHON" - <<'PY'
import os, socket, time, sys

host = os.environ["WAIT_HOST"]
port = int(os.environ["WAIT_PORT"])
timeout_seconds = float(os.environ["WAIT_TIMEOUT_SECONDS"])

deadline = time.time() + timeout_seconds
last_err = None
while time.time() < deadline:
    try:
        with socket.create_connection((host, port), timeout=1.0):
            sys.exit(0)
    except OSError as e:
        last_err = e
        time.sleep(0.2)

print(
    f"runbook.fail: tcp_not_ready host={host} port={port} last_err={type(last_err).__name__ if last_err else None}",
    file=sys.stderr,
)
sys.exit(1)
PY
}

_wait_for_worker_ready() {
  local timeout_seconds="$1"

  local deadline=$((SECONDS + timeout_seconds))
  while (( SECONDS < deadline )); do
    if [[ -n "$WORKER_PID" ]] && ! kill -0 "$WORKER_PID" >/dev/null 2>&1; then
      echo "runbook.fail: worker_exited_early pid=$WORKER_PID" >&2
      return 1
    fi

    if [[ -f "$WORKER_LOG" ]] && grep -q "temporal.worker.polling" "$WORKER_LOG"; then
      return 0
    fi

    sleep 0.2
  done

  echo "runbook.fail: worker_not_ready timeout_seconds=$timeout_seconds" >&2
  return 1
}

echo "runbook: ensuring_docker_compose_stack" >&2
# Idempotent even if already running.
docker compose up -d postgres temporal temporal-ui >/dev/null

# Basic readiness checks (these are about the stack, not the worker).
DB_HOST="${SPS_DB_HOST:-127.0.0.1}"
DB_PORT="${SPS_DB_PORT:-5432}"

# Settings supports both SPS_TEMPORAL_ADDRESS and TEMPORAL_ADDRESS.
TEMPORAL_ADDRESS="${SPS_TEMPORAL_ADDRESS:-${TEMPORAL_ADDRESS:-localhost:7233}}"
TEMPORAL_HOST="${TEMPORAL_ADDRESS%:*}"
TEMPORAL_PORT="${TEMPORAL_ADDRESS##*:}"
if [[ "$TEMPORAL_HOST" == "$TEMPORAL_PORT" ]]; then
  # No ':' in the address.
  TEMPORAL_HOST="$TEMPORAL_ADDRESS"
  TEMPORAL_PORT="7233"
fi

_wait_for_tcp "$DB_HOST" "$DB_PORT" 30
_wait_for_tcp "$TEMPORAL_HOST" "$TEMPORAL_PORT" 30

echo "runbook: applying_migrations" >&2
"$ALEMBIC" upgrade head >/dev/null

mkdir -p "$ROOT_DIR/artifacts/runbook"
WORKER_LOG="$ROOT_DIR/artifacts/runbook/m002_s03_worker_$(date +%Y%m%d_%H%M%S)_$$.log"

echo "runbook: starting_worker log=$WORKER_LOG" >&2
"$PYTHON" -m sps.workflows.worker >"$WORKER_LOG" 2>&1 &
WORKER_PID=$!

_wait_for_worker_ready 30

echo "runbook: worker_ready pid=$WORKER_PID" >&2

CASE_ID="${CASE_ID:-M002-S03-$(date +%Y%m%d%H%M%S)-$$}"
DECISION_OUTCOME="${DECISION_OUTCOME:-ACCEPT}"
REVIEWER_ID="${REVIEWER_ID:-reviewer-runbook}"
SUBJECT_AUTHOR_ID="${SUBJECT_AUTHOR_ID:-author-runbook}"
DECISION_ID="${DECISION_ID:-DEC-${CASE_ID}}"
REVIEWER_API_KEY="${SPS_REVIEWER_API_KEY:-dev-reviewer-key}"

echo "runbook: starting_workflow case_id=$CASE_ID" >&2
START_OUT="$("$PYTHON" -m sps.workflows.cli start --case-id "$CASE_ID")"

WORKFLOW_ID="$(printf "%s\n" "$START_OUT" | sed -n 's/.*workflow_id=\([^ ]*\).*/\1/p' | head -n1)"
RUN_ID="$(printf "%s\n" "$START_OUT" | sed -n 's/.*run_id=\([^ ]*\).*/\1/p' | head -n1)"

if [[ -z "$WORKFLOW_ID" || -z "$RUN_ID" ]]; then
  echo "runbook.fail: could_not_parse_workflow_ids" >&2
  echo "runbook.diagnostics: start_output" >&2
  printf "%s\n" "$START_OUT" >&2
  exit 1
fi

echo "workflow_id=$WORKFLOW_ID run_id=$RUN_ID case_id=$CASE_ID" >&2

echo "runbook: posting_review_decision decision_id=$DECISION_ID outcome=$DECISION_OUTCOME reviewer_id=$REVIEWER_ID" >&2
RESULT_JSON="$(RUNBOOK_CASE_ID="$CASE_ID" \
RUNBOOK_DECISION_ID="$DECISION_ID" \
RUNBOOK_DECISION_OUTCOME="$DECISION_OUTCOME" \
RUNBOOK_REVIEWER_ID="$REVIEWER_ID" \
RUNBOOK_SUBJECT_AUTHOR_ID="$SUBJECT_AUTHOR_ID" \
RUNBOOK_REVIEWER_API_KEY="$REVIEWER_API_KEY" \
"$PYTHON" - <<'PY'
import asyncio
import json
import os
import sys

import httpx

from sps.api.main import app
from sps.workflows.temporal import connect_client


async def main() -> int:
    case_id = os.environ["RUNBOOK_CASE_ID"]
    decision_id = os.environ["RUNBOOK_DECISION_ID"]
    decision_outcome = os.environ["RUNBOOK_DECISION_OUTCOME"]
    reviewer_id = os.environ["RUNBOOK_REVIEWER_ID"]
    subject_author_id = os.environ["RUNBOOK_SUBJECT_AUTHOR_ID"]
    reviewer_api_key = os.environ["RUNBOOK_REVIEWER_API_KEY"]

    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://runbook") as client:
        response = await client.post(
            "/api/v1/reviews/decisions",
            headers={"X-Reviewer-Api-Key": reviewer_api_key},
            json={
                "decision_id": decision_id,
                "idempotency_key": f"idem/{decision_id}",
                "case_id": case_id,
                "reviewer_id": reviewer_id,
                "subject_author_id": subject_author_id,
                "outcome": decision_outcome,
                "notes": "runbook m002/s03",
            },
        )
    if response.status_code not in (200, 201):
        print(
            f"runbook.fail: reviewer_api_post_failed status={response.status_code} body={response.text}",
            file=sys.stderr,
        )
        return 1

    client = await connect_client()
    handle = client.get_workflow_handle(f"permit-case/{case_id}")
    result = await handle.result()
    if hasattr(result, "model_dump"):
        print(json.dumps(result.model_dump(), sort_keys=True))
    else:
        print(json.dumps(result, sort_keys=True))
    return 0


raise SystemExit(asyncio.run(main()))
PY
)"

# Print the final result to stdout (operator copy/paste surface).
printf "%s\n" "$RESULT_JSON"

CORRELATION_ID="${WORKFLOW_ID}:${RUN_ID}"
REVIEW_KEY="idem/${DECISION_ID}"
REVIEW_DECISION_ID="$DECISION_ID"

# Defensive: keep SQL quoting safe.
pg_assert_no_single_quotes "$CORRELATION_ID"
pg_assert_no_single_quotes "$REVIEW_KEY"
pg_assert_no_single_quotes "$CASE_ID"

CID_QUOTED="$(pg_sql_quote "$CORRELATION_ID")"
RID_QUOTED="$(pg_sql_quote "$REVIEW_KEY")"
CASE_QUOTED="$(pg_sql_quote "$CASE_ID")"

echo "runbook: asserting_postgres correlation_id=$CORRELATION_ID" >&2

pg_assert_int_eq "select count(*) from case_transition_ledger where correlation_id=${CID_QUOTED}" "2" \
  "case_transition_ledger.count(correlation_id)"

pg_assert_int_eq "select count(*) from case_transition_ledger where correlation_id=${CID_QUOTED} and event_type='APPROVAL_GATE_DENIED'" "1" \
  "case_transition_ledger.count(APPROVAL_GATE_DENIED)"

pg_assert_int_eq "select count(*) from case_transition_ledger where correlation_id=${CID_QUOTED} and event_type='CASE_STATE_CHANGED'" "1" \
  "case_transition_ledger.count(CASE_STATE_CHANGED)"

pg_assert_int_eq "select count(*) from review_decisions where idempotency_key=${RID_QUOTED}" "1" \
  "review_decisions.count(idempotency_key)"

pg_assert_scalar_eq "select decision_id from review_decisions where idempotency_key=${RID_QUOTED}" "$REVIEW_DECISION_ID" \
  "review_decisions.decision_id"

pg_assert_scalar_eq "select case_id from review_decisions where idempotency_key=${RID_QUOTED}" "$CASE_ID" \
  "review_decisions.case_id"

echo "runbook: postgres_summary" >&2
pg_print "select event_type, count(*) from case_transition_ledger where correlation_id=${CID_QUOTED} group by event_type order by event_type" >&2
pg_print "select decision_id, idempotency_key, decision_outcome from review_decisions where idempotency_key=${RID_QUOTED}" >&2

echo "runbook: ok" >&2
