#!/usr/bin/env bash
# shellcheck shell=bash
set -euo pipefail

# M003 / S01 runbook verification: HTTP reviewer API → Temporal signal → workflow unblock.
#
# What this does:
#   1) Ensures docker compose services are up (Postgres + Temporal + Temporal UI + API)
#   2) Applies Alembic migrations
#   3) Starts the real worker entrypoint (python -m sps.workflows.worker)
#   4) Starts the FastAPI server (uvicorn sps.api.main:app)
#   5) Starts a PermitCaseWorkflow via the operator CLI
#   6) Drives the workflow via HTTP POST to /api/v1/reviews/decisions (the HTTP authority boundary)
#   7) Asserts: HTTP 201, review_decisions row in Postgres, APPROVED_FOR_SUBMISSION in ledger
#   8) Proves the 409 idempotency-conflict path (same idempotency_key + different decision_id)
#
# Key differences from m002_s03:
#   - Uses HTTP POST to reviewer API instead of operator CLI signal injection
#   - Verifies review_decisions row written by the API (not the activity)
#   - Verifies the HTTP 409 idempotency-conflict path
#
# Expected env vars (optional; defaults match src/sps/config.py and .env.example):
#   SPS_DB_HOST (default: localhost)
#   SPS_DB_PORT (default: 5432)
#   SPS_DB_NAME (default: sps)
#   SPS_DB_USER (default: sps)
#   SPS_DB_PASSWORD (default: sps)          # never printed
#
#   SPS_TEMPORAL_ADDRESS (default: localhost:7233)
#   SPS_TEMPORAL_NAMESPACE (default: default)
#   SPS_TEMPORAL_TASK_QUEUE (default: sps-permit-case)
#
#   SPS_REVIEWER_API_KEY (default: dev-reviewer-key)
#
#   API_HOST (default: localhost)
#   API_PORT (default: 8000)
#
# Optional overrides:
#   PYTHON (default: ./.venv/bin/python)
#   ALEMBIC (default: ./.venv/bin/alembic)
#   CASE_ID (default: autogenerated)
#   DECISION_OUTCOME (default: ACCEPT)
#   REVIEWER_ID (default: reviewer-runbook)

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# shellcheck source=scripts/lib/assert_postgres.sh
source "$ROOT_DIR/scripts/lib/assert_postgres.sh"

PYTHON="${PYTHON:-$ROOT_DIR/.venv/bin/python}"
ALEMBIC="${ALEMBIC:-$ROOT_DIR/.venv/bin/alembic}"

if [[ ! -x "$PYTHON" ]]; then
  echo "runbook.fail: python_not_found path=$PYTHON" >&2
  exit 2
fi

if [[ ! -x "$ALEMBIC" ]]; then
  echo "runbook.fail: alembic_not_found path=$ALEMBIC" >&2
  exit 2
fi

# Reviewer API key — never printed or echoed.
REVIEWER_API_KEY="${SPS_REVIEWER_API_KEY:-dev-reviewer-key}"
API_HOST="${API_HOST:-localhost}"
API_PORT="${API_PORT:-8000}"
API_BASE="http://${API_HOST}:${API_PORT}"

WORKER_PID=""
WORKER_LOG=""
API_PID=""
API_LOG=""

_cleanup() {
  local exit_code=$?

  if [[ -n "$API_PID" ]]; then
    if kill -0 "$API_PID" >/dev/null 2>&1; then
      echo "runbook.cleanup: stopping_api pid=$API_PID" >&2
      kill "$API_PID" >/dev/null 2>&1 || true
      wait "$API_PID" >/dev/null 2>&1 || true
    fi
  fi

  if [[ -n "$WORKER_PID" ]]; then
    if kill -0 "$WORKER_PID" >/dev/null 2>&1; then
      echo "runbook.cleanup: stopping_worker pid=$WORKER_PID" >&2
      kill "$WORKER_PID" >/dev/null 2>&1 || true
      wait "$WORKER_PID" >/dev/null 2>&1 || true
    fi
  fi

  if [[ $exit_code -ne 0 ]]; then
    if [[ -n "$WORKER_LOG" && -f "$WORKER_LOG" ]]; then
      echo "runbook.diagnostics: worker_log_tail path=$WORKER_LOG" >&2
      tail -n 50 "$WORKER_LOG" >&2 || true
    fi
    if [[ -n "$API_LOG" && -f "$API_LOG" ]]; then
      echo "runbook.diagnostics: api_log_tail path=$API_LOG" >&2
      tail -n 50 "$API_LOG" >&2 || true
    fi
  fi

  return $exit_code
}
trap _cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

_wait_for_tcp() {
  local host="$1"
  local port="$2"
  local timeout_seconds="$3"

  WAIT_HOST="$host" WAIT_PORT="$port" WAIT_TIMEOUT_SECONDS="$timeout_seconds" \
    "$PYTHON" - <<'PY'
import os, socket, time, sys

host = os.environ["WAIT_HOST"]
port = int(os.environ["WAIT_PORT"])
timeout_seconds = float(os.environ["WAIT_TIMEOUT_SECONDS"])

deadline = time.time() + timeout_seconds
last_err = None
while time.time() < deadline:
    try:
        with socket.create_connection((host, port), timeout=1.0):
            sys.exit(0)
    except OSError as e:
        last_err = e
        time.sleep(0.2)

print(
    f"runbook.fail: tcp_not_ready host={host} port={port} last_err={type(last_err).__name__ if last_err else None}",
    file=sys.stderr,
)
sys.exit(1)
PY
}

_wait_for_worker_ready() {
  local timeout_seconds="$1"

  local deadline=$((SECONDS + timeout_seconds))
  while (( SECONDS < deadline )); do
    if [[ -n "$WORKER_PID" ]] && ! kill -0 "$WORKER_PID" >/dev/null 2>&1; then
      echo "runbook.fail: worker_exited_early pid=$WORKER_PID" >&2
      return 1
    fi

    if [[ -f "$WORKER_LOG" ]] && grep -q "temporal.worker.polling" "$WORKER_LOG"; then
      return 0
    fi

    sleep 0.2
  done

  echo "runbook.fail: worker_not_ready timeout_seconds=$timeout_seconds" >&2
  return 1
}

_wait_for_api_ready() {
  local timeout_seconds="$1"

  local deadline=$((SECONDS + timeout_seconds))
  while (( SECONDS < deadline )); do
    if [[ -n "$API_PID" ]] && ! kill -0 "$API_PID" >/dev/null 2>&1; then
      echo "runbook.fail: api_exited_early pid=$API_PID" >&2
      return 1
    fi

    # The API is ready when its TCP port accepts connections.
    if "$PYTHON" - <<'PY' 2>/dev/null
import os, socket
try:
    with socket.create_connection(("localhost", int(os.environ.get("API_PORT", "8000"))), timeout=0.5):
        pass
    exit(0)
except OSError:
    exit(1)
PY
    then
      return 0
    fi

    sleep 0.2
  done

  echo "runbook.fail: api_not_ready timeout_seconds=$timeout_seconds" >&2
  return 1
}

_http_post_json() {
  # POST a JSON body and return the HTTP status code on stdout.
  # The response body goes to the file referenced by HTTP_RESPONSE_FILE.
  local url="$1"
  local body="$2"
  local api_key="$3"
  local out_file="${HTTP_RESPONSE_FILE:-/tmp/m003_s01_response_$$.json}"

  curl -s -o "$out_file" -w "%{http_code}" \
    -X POST "$url" \
    -H "Content-Type: application/json" \
    -H "X-Reviewer-Api-Key: ${api_key}" \
    -d "$body"
}

_assert_http_status() {
  local actual="$1"
  local expected="$2"
  local label="$3"

  if [[ "$actual" != "$expected" ]]; then
    echo "runbook.fail: http_status_mismatch label=$label expected=$expected actual=$actual" >&2
    if [[ -f "${HTTP_RESPONSE_FILE:-}" ]]; then
      echo "runbook.diagnostics: response_body" >&2
      cat "${HTTP_RESPONSE_FILE}" >&2 || true
    fi
    exit 1
  fi
}

_poll_ledger_for_state() {
  # Poll case_transition_ledger until CASE_STATE_CHANGED/APPROVED_FOR_SUBMISSION appears.
  local case_id_quoted="$1"
  local timeout_seconds="$2"

  local deadline=$((SECONDS + timeout_seconds))
  while (( SECONDS < deadline )); do
    local count
    count="$(pg_exec "select count(*) from case_transition_ledger where case_id=${case_id_quoted} and event_type='CASE_STATE_CHANGED' and to_state='APPROVED_FOR_SUBMISSION'" 2>/dev/null || echo 0)"
    count="${count%$'\n'}"
    if [[ "$count" == "1" ]]; then
      return 0
    fi
    sleep 0.5
  done

  echo "runbook.fail: workflow_not_approved_for_submission case_id=${case_id_quoted} timeout=${timeout_seconds}s" >&2
  return 1
}

# ---------------------------------------------------------------------------
# Phase 1: Ensure infrastructure is up
# ---------------------------------------------------------------------------

echo "runbook: ensuring_docker_compose_stack" >&2
docker compose up -d postgres temporal temporal-ui >/dev/null

DB_HOST="${SPS_DB_HOST:-127.0.0.1}"
DB_PORT="${SPS_DB_PORT:-5432}"
TEMPORAL_ADDRESS="${SPS_TEMPORAL_ADDRESS:-${TEMPORAL_ADDRESS:-localhost:7233}}"
TEMPORAL_HOST="${TEMPORAL_ADDRESS%:*}"
TEMPORAL_PORT="${TEMPORAL_ADDRESS##*:}"
if [[ "$TEMPORAL_HOST" == "$TEMPORAL_PORT" ]]; then
  TEMPORAL_HOST="$TEMPORAL_ADDRESS"
  TEMPORAL_PORT="7233"
fi

_wait_for_tcp "$DB_HOST" "$DB_PORT" 30
_wait_for_tcp "$TEMPORAL_HOST" "$TEMPORAL_PORT" 30

# ---------------------------------------------------------------------------
# Phase 2: Migrations
# ---------------------------------------------------------------------------

echo "runbook: applying_migrations" >&2
"$ALEMBIC" upgrade head >/dev/null

# ---------------------------------------------------------------------------
# Phase 3: Start worker
# ---------------------------------------------------------------------------

mkdir -p "$ROOT_DIR/artifacts/runbook"
WORKER_LOG="$ROOT_DIR/artifacts/runbook/m003_s01_worker_$(date +%Y%m%d_%H%M%S)_$$.log"

echo "runbook: starting_worker log=$WORKER_LOG" >&2
"$PYTHON" -m sps.workflows.worker >"$WORKER_LOG" 2>&1 &
WORKER_PID=$!

_wait_for_worker_ready 30
echo "runbook: worker_ready pid=$WORKER_PID" >&2

# ---------------------------------------------------------------------------
# Phase 4: Start FastAPI server
# ---------------------------------------------------------------------------

API_LOG="$ROOT_DIR/artifacts/runbook/m003_s01_api_$(date +%Y%m%d_%H%M%S)_$$.log"

echo "runbook: starting_api log=$API_LOG port=$API_PORT" >&2
"$PYTHON" -m uvicorn sps.api.main:app --host 0.0.0.0 --port "$API_PORT" >"$API_LOG" 2>&1 &
API_PID=$!

_wait_for_api_ready 30
echo "runbook: api_ready pid=$API_PID" >&2

# ---------------------------------------------------------------------------
# Phase 5: Start workflow
# ---------------------------------------------------------------------------

CASE_ID="${CASE_ID:-M003-S01-$(date +%Y%m%d%H%M%S)-$$}"
DECISION_OUTCOME="${DECISION_OUTCOME:-ACCEPT}"
REVIEWER_ID="${REVIEWER_ID:-reviewer-runbook}"

echo "runbook: starting_workflow case_id=$CASE_ID" >&2
START_OUT="$("$PYTHON" -m sps.workflows.cli start --case-id "$CASE_ID")"

WORKFLOW_ID="$(printf "%s\n" "$START_OUT" | sed -n 's/.*workflow_id=\([^ ]*\).*/\1/p' | head -n1)"
RUN_ID="$(printf "%s\n" "$START_OUT" | sed -n 's/.*run_id=\([^ ]*\).*/\1/p' | head -n1)"

if [[ -z "$WORKFLOW_ID" || -z "$RUN_ID" ]]; then
  echo "runbook.fail: could_not_parse_workflow_ids" >&2
  echo "runbook.diagnostics: start_output" >&2
  printf "%s\n" "$START_OUT" >&2
  exit 1
fi

echo "workflow_id=$WORKFLOW_ID run_id=$RUN_ID case_id=$CASE_ID" >&2

# ---------------------------------------------------------------------------
# Phase 6: Wait for workflow to enter REVIEW_PENDING (APPROVAL_GATE_DENIED in ledger)
# ---------------------------------------------------------------------------

echo "runbook: waiting_for_workflow_to_enter_review_pending" >&2

# Defensive: wait for the APPROVAL_GATE_DENIED ledger row (proves the workflow is paused).
pg_assert_no_single_quotes "$CASE_ID"
CASE_QUOTED="$(pg_sql_quote "$CASE_ID")"

_poll_denial_row() {
  local timeout_seconds="$1"
  local deadline=$((SECONDS + timeout_seconds))
  while (( SECONDS < deadline )); do
    local count
    count="$(pg_exec "select count(*) from case_transition_ledger where case_id=${CASE_QUOTED} and event_type='APPROVAL_GATE_DENIED'" 2>/dev/null || echo 0)"
    count="${count%$'\n'}"
    if [[ "$count" == "1" ]]; then
      return 0
    fi
    sleep 0.5
  done
  echo "runbook.fail: workflow_did_not_enter_review_pending case_id=$CASE_ID timeout=${timeout_seconds}s" >&2
  return 1
}
_poll_denial_row 30
echo "runbook: workflow_in_review_pending" >&2

# ---------------------------------------------------------------------------
# Phase 7: POST to reviewer API (the HTTP authority boundary)
# ---------------------------------------------------------------------------

DECISION_ID="DEC-$(date +%Y%m%d%H%M%S)-$$"
IDEMPOTENCY_KEY="runbook/${WORKFLOW_ID}"

echo "runbook: posting_review_decision decision_id=$DECISION_ID outcome=$DECISION_OUTCOME" >&2

HTTP_RESPONSE_FILE="$(mktemp /tmp/m003_s01_resp_XXXXXX.json)"
export HTTP_RESPONSE_FILE

DECISION_BODY="$(cat <<JSON
{
  "decision_id": "${DECISION_ID}",
  "idempotency_key": "${IDEMPOTENCY_KEY}",
  "case_id": "${CASE_ID}",
  "reviewer_id": "${REVIEWER_ID}",
  "outcome": "${DECISION_OUTCOME}"
}
JSON
)"

HTTP_STATUS="$(_http_post_json \
  "${API_BASE}/api/v1/reviews/decisions" \
  "$DECISION_BODY" \
  "$REVIEWER_API_KEY")"

_assert_http_status "$HTTP_STATUS" "201" "post_review_decision"

echo "runbook: reviewer_api_201_ok decision_id=$DECISION_ID" >&2

# Print the 201 response to stdout (operator surface).
if [[ -f "$HTTP_RESPONSE_FILE" ]]; then
  cat "$HTTP_RESPONSE_FILE"
  echo
fi

# ---------------------------------------------------------------------------
# Phase 8: Assert review_decisions row in Postgres
# ---------------------------------------------------------------------------

pg_assert_no_single_quotes "$DECISION_ID"
pg_assert_no_single_quotes "$IDEMPOTENCY_KEY"

DEC_QUOTED="$(pg_sql_quote "$DECISION_ID")"
IDEM_QUOTED="$(pg_sql_quote "$IDEMPOTENCY_KEY")"

echo "runbook: asserting_review_decisions_row" >&2

pg_assert_int_eq \
  "select count(*) from review_decisions where decision_id=${DEC_QUOTED}" \
  "1" \
  "review_decisions.count(decision_id)"

pg_assert_scalar_eq \
  "select case_id from review_decisions where decision_id=${DEC_QUOTED}" \
  "$CASE_ID" \
  "review_decisions.case_id"

pg_assert_scalar_eq \
  "select decision_outcome from review_decisions where decision_id=${DEC_QUOTED}" \
  "$DECISION_OUTCOME" \
  "review_decisions.decision_outcome"

pg_assert_scalar_eq \
  "select idempotency_key from review_decisions where decision_id=${DEC_QUOTED}" \
  "$IDEMPOTENCY_KEY" \
  "review_decisions.idempotency_key"

echo "runbook: review_decisions_row_ok" >&2

# ---------------------------------------------------------------------------
# Phase 9: Wait for workflow to complete with APPROVED_FOR_SUBMISSION
# ---------------------------------------------------------------------------

echo "runbook: waiting_for_workflow_completion" >&2
_poll_ledger_for_state "$CASE_QUOTED" 30
echo "runbook: workflow_completed_approved_for_submission" >&2

pg_assert_int_eq \
  "select count(*) from case_transition_ledger where case_id=${CASE_QUOTED} and event_type='CASE_STATE_CHANGED' and to_state='APPROVED_FOR_SUBMISSION'" \
  "1" \
  "case_transition_ledger.CASE_STATE_CHANGED.APPROVED_FOR_SUBMISSION"

# ---------------------------------------------------------------------------
# Phase 10: Prove 409 idempotency-conflict path
# ---------------------------------------------------------------------------

echo "runbook: proving_409_idempotency_conflict" >&2

CONFLICT_DECISION_ID="DEC-CONFLICT-$(date +%Y%m%d%H%M%S)-$$"

CONFLICT_BODY="$(cat <<JSON
{
  "decision_id": "${CONFLICT_DECISION_ID}",
  "idempotency_key": "${IDEMPOTENCY_KEY}",
  "case_id": "${CASE_ID}",
  "reviewer_id": "${REVIEWER_ID}",
  "outcome": "${DECISION_OUTCOME}"
}
JSON
)"

HTTP_STATUS_409="$(_http_post_json \
  "${API_BASE}/api/v1/reviews/decisions" \
  "$CONFLICT_BODY" \
  "$REVIEWER_API_KEY")"

_assert_http_status "$HTTP_STATUS_409" "409" "post_review_decision_conflict"

echo "runbook: reviewer_api_409_ok idempotency_key=$IDEMPOTENCY_KEY" >&2

# ---------------------------------------------------------------------------
# Phase 11: Failure path verification — missing/wrong API key → 401
# ---------------------------------------------------------------------------

echo "runbook: verifying_401_on_missing_key" >&2
STATUS_401_MISSING="$(curl -s -o /dev/null -w "%{http_code}" \
  -X POST "${API_BASE}/api/v1/reviews/decisions" \
  -H "Content-Type: application/json" \
  -d '{}')"

_assert_http_status "$STATUS_401_MISSING" "401" "missing_api_key"

echo "runbook: verifying_401_on_wrong_key" >&2
STATUS_401_WRONG="$(curl -s -o /dev/null -w "%{http_code}" \
  -X POST "${API_BASE}/api/v1/reviews/decisions" \
  -H "Content-Type: application/json" \
  -H "X-Reviewer-Api-Key: wrong-key-definitely-not-valid" \
  -d '{}')"

_assert_http_status "$STATUS_401_WRONG" "401" "wrong_api_key"

echo "runbook: auth_checks_ok" >&2

# ---------------------------------------------------------------------------
# Phase 12: Final Postgres summary
# ---------------------------------------------------------------------------

echo "runbook: postgres_summary" >&2
pg_print "select event_type, to_state, count(*) from case_transition_ledger where case_id=${CASE_QUOTED} group by event_type, to_state order by event_type" >&2
pg_print "select decision_id, idempotency_key, decision_outcome from review_decisions where decision_id=${DEC_QUOTED}" >&2

# Signal inspection hint for operators.
echo "runbook: structured_log_hint hint='docker compose logs api | grep reviewer_api'" >&2

echo "runbook: ok" >&2
